monthly_income=int(input("Enter your monthly income: "))
monthly_expenses=int(input("Enter your total monthly expenses:"))
S=(monthly_income-monthly_expenses)
AS=int(S*12+S*12*0.05)
print("Your monthly savings are $",S)
print("Projected savings after one year, with interest, is: $",AS)
